import React, { useState, useEffect } from 'react';
import { SentenceRecord } from '../types';
import { X, Copy, Check, Download, Printer, FileText } from 'lucide-react';

interface ExportModalProps {
  isOpen: boolean;
  onClose: () => void;
  record: SentenceRecord | null;
}

export const ExportModal: React.FC<ExportModalProps> = ({
  isOpen,
  onClose,
  record
}) => {
  const [copied, setCopied] = useState(false);

  // ESC 키로 모달 닫기
  useEffect(() => {
    if (!isOpen) return;
    const handleKeyDown = (e: KeyboardEvent) => {
      if (e.key === 'Escape') {
        onClose();
      }
    };
    window.addEventListener('keydown', handleKeyDown);
    return () => window.removeEventListener('keydown', handleKeyDown);
  }, [isOpen, onClose]);

  if (!isOpen || !record) return null;

  const isAnalysis = record.mode === 'analysis';
  const modeLabel = isAnalysis ? '가져온 글 분석 (타인 문장)' : '내가 쓴 글 교정 (본인 문장)';
  const dateStr = new Date(record.createdAt).toLocaleDateString('ko-KR', {
    year: 'numeric',
    month: 'long',
    day: 'numeric'
  });

  const markdownContent = `# Pentalyze : 다섯결 리포트

- **일자**: ${dateStr}
- **모드**: ${modeLabel}
- **종합 요약**: ${record.summaryShort}

---

## 📌 분석 대상 문장
> "${record.originalText}"

---

### [1단계] ${record.steps.step1.title} (${record.steps.step1.subtitle})
${record.steps.step1.mainContent}

**세부 포인트:**
${record.steps.step1.details.map((d) => `- ${d}`).join('\n')}

*가이드: ${record.steps.step1.actionableAdvice || 'N/A'}*

---

### [2단계] ${record.steps.step2.title} (${record.steps.step2.subtitle})
${record.steps.step2.mainContent}

**세부 포인트:**
${record.steps.step2.details.map((d) => `- ${d}`).join('\n')}

*가이드: ${record.steps.step2.actionableAdvice || 'N/A'}*

---

### [3단계] ${record.steps.step3.title} (${record.steps.step3.subtitle})
${record.steps.step3.mainContent}

**세부 포인트:**
${record.steps.step3.details.map((d) => `- ${d}`).join('\n')}

*가이드: ${record.steps.step3.actionableAdvice || 'N/A'}*

---

### [4단계] ${record.steps.step4.title} (${record.steps.step4.subtitle})
${record.steps.step4.mainContent}

**세부 포인트:**
${record.steps.step4.details.map((d) => `- ${d}`).join('\n')}

*가이드: ${record.steps.step4.actionableAdvice || 'N/A'}*

---

### [5단계] ${record.steps.step5.title} (${record.steps.step5.subtitle})
${record.steps.step5.mainContent}

**세부 포인트:**
${record.steps.step5.details.map((d) => `- ${d}`).join('\n')}

*가이드: ${record.steps.step5.actionableAdvice || 'N/A'}*

---
*Generated by Pentalyze (다섯결) - 5-Step Sentence Insights*
`;

  const handleCopyMarkdown = () => {
    navigator.clipboard.writeText(markdownContent);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownloadMarkdown = () => {
    const blob = new Blob([markdownContent], { type: 'text/markdown;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `pentalyze_${record.id}_report.md`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  const handlePrint = () => {
    window.print();
  };

  return (
    <div 
      className="fixed inset-0 z-[9999] flex items-center justify-center p-3 sm:p-4 bg-black/80 backdrop-blur-md animate-fadeIn"
      onClick={(e) => {
        if (e.target === e.currentTarget) onClose();
      }}
    >
      <div className="relative w-full max-w-2xl max-h-[90vh] overflow-y-auto rounded-2xl border border-white/10 bg-[#17181c] p-5 sm:p-6 shadow-2xl text-zinc-200">
        
        {/* Header */}
        <div className="flex items-center justify-between pb-4 border-b border-white/10">
          <div className="flex items-center gap-2">
            <FileText className="w-5 h-5 text-amber-400" />
            <h2 className="text-xl font-bold font-serif-kr text-white">
              다섯결 리포트 내보내기
            </h2>
          </div>
          <button
            type="button"
            onClick={onClose}
            className="p-1.5 rounded-lg text-zinc-400 hover:text-white hover:bg-white/5 transition-colors"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Quick Actions */}
        <div className="mt-4 flex flex-wrap items-center gap-2.5">
          <button
            type="button"
            onClick={handleCopyMarkdown}
            className="flex items-center gap-1.5 px-3.5 py-2 rounded-xl bg-amber-500 text-black font-semibold text-xs transition-all hover:bg-amber-400"
          >
            {copied ? <Check className="w-3.5 h-3.5" /> : <Copy className="w-3.5 h-3.5" />}
            <span>{copied ? '복사되었습니다!' : '마크다운 복사'}</span>
          </button>

          <button
            type="button"
            onClick={handleDownloadMarkdown}
            className="flex items-center gap-1.5 px-3.5 py-2 rounded-xl bg-white/10 hover:bg-white/15 text-zinc-200 text-xs font-medium transition-colors"
          >
            <Download className="w-3.5 h-3.5" />
            <span>.md 파일 다운로드</span>
          </button>

          <button
            type="button"
            onClick={handlePrint}
            className="flex items-center gap-1.5 px-3.5 py-2 rounded-xl bg-white/10 hover:bg-white/15 text-zinc-200 text-xs font-medium transition-colors"
          >
            <Printer className="w-3.5 h-3.5" />
            <span>인쇄 / PDF 저장</span>
          </button>
        </div>

        {/* Preview Markdown Box */}
        <div className="mt-4">
          <label className="block text-xs font-medium text-zinc-400 mb-2">리포트 미리보기</label>
          <pre className="p-4 rounded-xl bg-black/50 border border-white/10 text-xs text-zinc-300 font-mono overflow-x-auto whitespace-pre-wrap max-h-96 leading-relaxed">
            {markdownContent}
          </pre>
        </div>

        {/* Footer */}
        <div className="mt-5 pt-3 border-t border-white/10 flex justify-end">
          <button
            type="button"
            onClick={onClose}
            className="px-4 py-2 rounded-xl bg-white/5 hover:bg-white/10 text-xs text-zinc-300 transition-colors"
          >
            닫기
          </button>
        </div>
      </div>
    </div>
  );
};
